language: python

sudo: false

env:
  - TOX_ENV=docs
  - TOX_ENV=flake
  - TOX_ENV=py27-django1.6-drf3.1
  - TOX_ENV=py27-django1.7-drf3.1
  - TOX_ENV=py32-django1.6-drf3.1
  - TOX_ENV=py32-django1.7-drf3.1
  - TOX_ENV=py33-django1.6-drf3.1
  - TOX_ENV=py33-django1.7-drf3.1
  - TOX_ENV=py34-django1.6-drf3.1
  - TOX_ENV=py34-django1.7-drf3.1

matrix:
    fast_finish: true

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
